### ISSUE TITLE
Insert social media posts

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#10]

**Comment by FroudeDescartes** [comment]
@jpradocueva 
Can we define again what should this component do?

**Comment by jpradocueva** [comment]
See an example in Testimonials section, https://standards-hub.github.io/Generate_documentation_Nuxt/#testimonials
This refer a post on 23 Jan 2021. The content summarize the post, and views.

![image](https://github.com/standards-hub/docs/assets/3258579/be9f3cb8-c023-4a13-bdbb-9ef9cce01372)

**Comment by jpradocueva** [comment]
See code, here, https://github.com/standards-hub/Generate_documentation_Nuxt/edit/master/content/en/index.md

**Comment by FroudeDescartes** [comment]
**1. Doc for Twitter:**
https://vuejsexamples.com/create-a-twitter-testimonial-wall-for-your-nuxt-website/ - _this seems to be the only one that partially works_ 
https://developer.twitter.com/en/docs/twitter-for-websites/oembed-api#item1
https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview

**2. Doc for Meta:**
https://developers.facebook.com/docs/features-reference/oembed-read

**3. Doc for LinkedIn:**
https://www.linkedin.com/help/linkedin/answer/a529065/embed-content-from-the-linkedin-feed?lang=en
https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/follow-company-plugin - _Show followers_
https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/share-plugin - _Share to LinkedIn_

**Comment by FroudeDescartes** [comment]
@jpradocueva 
I have managed to embed posts from Facebook, LinkedIn and Twitter, but only with Twitter there is a problem of not showing number of likes, comments etc. whereas with Facebook and LinkedIn, everything is showing nicely. 
You can see this results at `http://localhost:3000/getting-started` below videos.

**Comment by FroudeDescartes** [comment]
Library used to represent Tweets:
https://github.com/timb-103/nuxt-testimonial
