### ISSUE TITLE
Create a Documentation in OMA

### ISSUE THREAD

**Issue by FroudeDescartes** [standards-hub/docs#102]
Create a separate content folder in [OMA](https://github.com/OpenMobileAlliance/oma-knowledge-base) for documenting each component, something like [here](https://ui.nuxt.com/getting-started/installation). One subfolder `Getting Started` , other `Components`

- [x] ShActionCard
- [x] ~~ShAdditionalMenu~~ renamed: ShAnnouncement
- [x] ShAlert
- [x] ShAvatar
- [x] ShBadge
- [x] ShCard ~~(needs update on **ui.config**)~~
- [x] ShCarousel
- [x] ShFacebook
- [x] ShLinkedin
- [x] ShMicroCard
- [x] ShTextImg
- [x] ShTweet
- [x] ShVideo
- [x] ShListCards
- [x] F.A.Q

Create an option for adding HTML-like comments in .md files

**Comment by FroudeDescartes** [comment]
Example on how to convert component to have all the necessary props and configs:
[Alert component](https://github.com/nuxt/ui/blob/dev/src/runtime/components/elements/Alert.vue)
[Alert config ](https://github.com/nuxt/ui/blob/dev/src/runtime/ui.config/elements/alert.ts)

**Comment by FroudeDescartes** [comment]
Dejan`s part will be to insert parserer so we can use full md in key: value pairs, ex:
```
subtitle: |
    check out [promptly]{ .text-blue-500}```

**Comment by FroudeDescartes** [comment]
https://github.com/nuxt/ui/blob/dev/docs/components/content/ComponentPreset.vue

**Comment by jpradocueva** [comment]
- [x] Update Dynamic Table & Spreadsheet with all the constructors as well as the guidelines.
