### ISSUE TITLE
ShTextImg Issues

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#104]
### Add Subtitle
1. We need to add `subtitle` property to be positioned below the title
2. `title` and `subtitle` size should be different
3. We need to have the ability to change the font type and size for the whole website but we must be able to overwrite font type and size per constructor.

### Issues with `status`
4. If we remove `status,` the text is displayed with a grey background and white text, which is not ideal for readability. We need to reconsider how we are working with this property.

5. It seems that it changes the background color of the whole constructor
* `status`
   * "on" = green
   * "off" = pink
   * "pending" = yellow
   * "highlight" = blue
Could we control the background color using the property `wrapper` but as style inside the `ui`? This will allow us to use `status` for a different type of effect or contrast. 

6. Use `status` as a way to get the right level of contrast between text and background color. This implies that if `status` is used, then `wrapper` and `text-color` will be overrun by `status`. 

High-contrast grayscale color combinations can enhance readability and accessibility. Here are some effective text and background color combinations in grayscale: (see new `status` values)

#### Black Text on White Background
* `status` = "B/B"
* Text Color: #000000 (Black)
* Background Color: #FFFFFF (White)
* Contrast Ratio: 21:1

#### White Text on Black Background
* `status` = W/B
* Text Color: #FFFFFF (White)
* Background Color: #000000 (Black)
* Contrast Ratio: 21:1

#### Dark Gray Text on Light Gray Background
* `status` = dG/lG
* Text Color: #333333 (Dark Gray)
* Background Color: #E0E0E0 (Light Gray)
* Contrast Ratio: 8.6:1

#### Light Gray Text on Dark Gray Background
* `status` = lG/dG
* Text Color: #E0E0E0 (Light Gray)
* Background Color: #333333 (Dark Gray)
* Contrast Ratio: 8.6:1

#### Medium Gray Text on White Background
* `status` = mG/W
* Text Color: #666666 (Medium Gray)
* Background Color: #FFFFFF (White)
* Contrast Ratio: 5.4:1

#### White Text on Medium Gray Background
* `status` = W/mG
* Text Color: #FFFFFF (White)
* Background Color: #666666 (Medium Gray)
* Contrast Ratio: 5.4:1

These combinations ensure a high level of contrast, making text easier to read, especially for individuals with visual impairments.

#### Black text on a Yellow background
* `status` = B/Y or "1"
* Text Color: #000000 (Black)
* Background Color: #FFFF00 (Yellow)
* Contrast Ratio: 19.6:1

#### Blue text on a Light Blue background
* `status` = BL/lB or "2"
* Text Color: #0000FF (Blue)
* Background Color: #ADD8E6 (Light Blue)
* Contrast Ratio: 8.6:1

#### Red text on a White background
* `status` = or "3"
* Text Color: #FF0000 (Red)
* Background Color: #FFFFFF (White)
* Contrast Ratio: 4.0:1
#### Green text on a Black background
* `status` = or "4"
* Text Color: #00FF00 (Green)
* Background Color: #000000 (Black)
* Contrast Ratio: 15.3:1

#### Navy Blue text on a Light Gray background
* `status` = or "5"
* Text Color: #000080 (Navy Blue)
* Background Color: #D3D3D3 (Light Gray)
* Contrast Ratio: 11.9:1

##### White text on a Red background
* `status` =  or "6"
* Text Color: #FFFFFF (White)
* Background Color: #FF0000 (Red)
* Contrast Ratio: 4.0:1

### Other examples
![image](https://github.com/standards-hub/docs/assets/3258579/7840fab4-4f0b-4c26-89c8-612e3f7f59f8)

We could use `status` in other constructors and apply this functionality. @FroudeDescartes what do you think?

**Comment by jpradocueva** [comment]
### `container` vs `wrapper`
I have noticed that to insert a shadow in this `ShTextImg` constructor, we need to use the property `container` rather than `wrapper` used on other constructors. I don't mind which one, but we need to be consistent.

**Comment by FroudeDescartes** [comment]
@jpradocueva 
- [x] Add Subtitle
- [x] Issues with Status:
   - [x] default status (or no status) now appears as grey bg with darker text for optimal contrast
   - [x] status is an option that targets the whole constructor, and by design it changes bg color and text color
   - [x] as a way to get the right level of contrast between text and background color (will work more on that)
- [x] making status available across the app (Dejan and I will have a meeting about this) **_@FroudeDescartes says: This is great idea btw_** EDIT: For now, styling will be available across the app while the logic must be inserted in the component itself. The reasoning behind this is that we don`t know which part of the component we want to change (to add status)
 so it must be manually inserted
 - [x] _container_ vs _wrapper_ - opted out to use _wrapper_ as it has been already used in all of the other components

**Comment by jpradocueva** [comment]
@FroudeDescartes See enhancements to the example on https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/21

**Comment by FroudeDescartes** [comment]
I have updated this component and update was the contrast used in the status section. I have implemented 4 options, just to try out, but we can change or adapt them however we like.
