### ISSUE TITLE
ShMicroCard Issues

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#105]
### Issues
1. In this constructor, it is used `wrapper`, but in others, the name is `container`. 
* We need to be consistent across constructors and use the same name in all the constructors.

2. Not `text` property
* Should we add `text` property to insert more text if needed?

3. `link` in markdown but `src` in the constructor logic
* In the logic, we should use the property names to avoid confusion.

4. How to remove the text underline? See the image below. I cannot find how to remove it. 

<img width="425" alt="image" src="https://github.com/standards-hub/docs/assets/3258579/bfce2ec9-a0fc-4b38-a19c-1b935847aa8f">

**Comment by FroudeDescartes** [comment]
This issue is resolved with this [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/20).
I will be closing this issue for now.

**Comment by jpradocueva** [comment]
@FroudeDescartes 
We use `src` property in this constructor instead of `url` or `href`. 
Can we define when to use each one of these three properties?

**Comment by FroudeDescartes** [comment]
> @FroudeDescartes We use `src` property in this constructor instead of `url` or `href`. Can we define when to use each one of these three properties?

@jpradocueva 
I will see by tomorrow to have a fully updated list with unified and assigned props to each constructor.
