### ISSUE TITLE
ActionCard: Comments

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#106]
### About Properties
- [x] `background`: Should this be called `backgroundImage` to avoid misunderstandings?
- [x] `text`: Should we add the option of a `text` property if we want to add notes?
- [x] `buttonLink`: Should we add a buttonLink to redirect a click to, e.g. a HubSpot web form?
- [x]  Also, the button needs some special effects to show the user that the button was clicked. 
- [x]  Should `icon` also have an `altIcon` property? These properties are used by SEOs to grade the content. If we add this property, then we should rename `altImage` for completeness.
- [ ] Default `buttonColor` should be grey, black or white color, to emphasize contrast. Currently, it seems green color.

**Comment by jpradocueva** [comment]
@FroudeDescartes, I have added some examples to PR https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/21/files

**Comment by FroudeDescartes** [comment]
[PR ](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/24)resolving listed issues

**Comment by jpradocueva** [comment]
If `buttonColor` is not present, then there is no color for the button. It is transparent.
