### ISSUE TITLE
ShCard: Comments

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#107]
@FroudeDescartes these are my observations so far on this particular constructor:

### Style
- [x] `text`: I cannot provide `text-color` for the inside of the card body text. See comments inline with the property in PR https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/23
- [x] `background` Also doesn't seem to work when it is applied as a style and the `image link` is removed. See also PR https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/23

### Other
Something is not right in this constructor. 
I added three sections, but the order in which the content is displayed and written in the markdown file is inconsistent.
Please review and approve PR as it is enhancing the guidelines.

**Comment by FroudeDescartes** [comment]
> * [ ]  `background` Also doesn't seem to work when it is applied as a style and the `image link` is removed. See also PR [Comments on Shcard constructor OpenMobileAlliance/oma-knowledge-base#23](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/23)

@jpradocueva 
 I have provided an answer for this in the linked PR, but we can discuss it at today's meeting

**Comment by FroudeDescartes** [comment]
> ### Other
> Something is not right in this constructor. I added three sections, but the order in which the content is displayed and written in the markdown file is inconsistent. Please review and approve PR as it is enhancing the guidelines.

@jpradocueva 
I am not sure what is this bug that you have described. Lets try it out at the meeting, to be sure what is going on.
