### ISSUE TITLE
ShAlert: Issues

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#109]
#### Problems
`text`: The content input into the`text` property in the `.md` file is applied to all the alerts constructors

See image below:
*This is what is written in markdown*

<img width="923" alt="2024-05-24_19-45-17" src="https://github.com/standards-hub/docs/assets/3258579/86d5ee6f-ce48-4ce5-91dc-9f3abb6fd217">

*but the `text` property content displays the same content (latest input) across all the alert constructors:*

![image](https://github.com/standards-hub/docs/assets/3258579/a3cc8145-f0cc-4dd0-ac80-7f6c7c8b8939)

This constructor is not working as expected.
- [x] text disappear when adding style to the `wrapper` property.
- [x]  how to control the width of the wrapper to make it shorter or larger?

**Comment by FroudeDescartes** [comment]
@jpradocueva 
Issues resolved in [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/27).

Summarize:
- Addressed issue with text rendering on `success `and `warning` type of alert. 
- This should also reflect on styling of `wrapper`.
- For control over width of `wrapper` we have to use **`w-fit`** class inside of it. This will allow us to span the wrapper for the length of content inside.

Please, checkout the PR and see if there are any issues with it. If everything is good, we can close this issue.
