### ISSUE TITLE
Look & Feel Configuration: Style Requirements

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#111]
In the current oma-knowledge-base website, we need to update the following configuration properties:

- [x] Top Menus: font type and size
- [x] General content font type  and size
- [x] H1 to H7 font type and size
- [x] Primary, secondary colors
- [x] URL font type and color; URL behavior
- [x] Code font type and color
- [x] Remove underline for H1-H7
- [x] Update site and components to support dark theme
- [x] Add font-weight //problem adding weight to H1-H7
- [x] Add font color // problem with adding colors
- [x] Add loading indicator `<NuxtLoadingIndicator />` (add to `app.vue` before `<NuxtPage />`)
- [x] Add previous/next page
- [x] Add ToC
- [x] Add copy button to block-code
- [ ] Add pointer highlight as shown in [issue](https://github.com/orgs/standards-hub/projects/5?pane=issue&itemId=72355381) 
- Any other look & feel style that we need to configure for each prospective customer

We can start identifying where on how to modify it and then expose these styling via a configuration file and properties.

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/56) related to this issue
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/57) related to dark mode
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/70) related to loading indicator
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/73) related to previous/next page button

**Comment by jpradocueva** [comment]
@FroudeDescartes, I have been looking for options regarding what look and feel to manipulate. I want to check with you what you think. This document [font-family-examples-3.html](https://drive.google.com/file/d/1m_HInggvIU0zK3dX_jSYeEO8Ccxnjbmy/view?usp=drive_link) contains options to manipulate the style of few elements, e.g. code, body, menus, etc.
We could create nice effects by combining font weights like `light` (300), `regular` (400), or `bold` (700), as suggested in the file.
Please check the attached file and think about what it will take to have this level of control exposed in the `app.config.ts` file.

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/142) related to the following issues

**Comment by jpradocueva** [comment]
@FroudeDescartes 
I have been doing some research about using different colors for each of the section headers. What do you think?

### Dark Mode
To create a well-balanced color scheme for headers that transition from darker to lighter tones based on the H1 color (#E7D6C2), we can use progressively lighter shades for each subsequent header level. Here’s a proposed scheme:

H1: #E7D6C2 (base color)
H2: Darker variation – #D3C1AC (a slightly more muted tone than H1)
H3: #C0AC96 (darker and more subdued, offering strong contrast)
H4: #AA977F (a moderate contrast, stepping closer to mid-tone)
H5: #96826A (a soft, darker shade that complements the previous ones without being too bold)

### Light Mode
Let's see how it looks like then we can find out different tones for the light mode.

**Comment by jpradocueva** [comment]
@FroudeDescartes, just in case you are not aware, the style changes where we add a container around images, as well as the HubSpot forms, haven't been incorporated into the `development` branch yet.

See:

![image](https://github.com/user-attachments/assets/7526d02b-bf78-4597-8e4a-5a80d701463a)

![image](https://github.com/user-attachments/assets/1338f99d-dec5-4133-91b2-bff7edbbafa6)

**Comment by FroudeDescartes** [comment]
@jpradocueva 
Thanks for update about image container. These changes will be incorporated in my next commit.

**Comment by FroudeDescartes** [comment]
About HubSpot change, that is really weird because I have ran the site from temp URL many times and each time it rendered those changes perfectly. Let`s see if @gocadimic can repeat this bug in her local development server and on live version.

**Comment by jpradocueva** [comment]
@FroudeDescartes, I agree; when I test the "contact us" and "newsletter," I find that on only one occasion, the "newsletter" displays the correct HubSpot dark mode, then stops doing it. Very strange!

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/405) resolving Copy button

**Comment by jpradocueva** [comment]
This is closed now.
