### ISSUE TITLE
Problem rendering a submenu index.

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#113]
@FroudeDescartes, Filip there isa problem rendering an `index.md` file in the following folder:  `omaspecsworks/collaborate/affiliates/`index.md. I am doing something wrong, but I cannot see the problem. Could you please investigate? Thanks

**Comment by FroudeDescartes** [comment]
![image](https://github.com/standards-hub/docs/assets/128386451/9231ef13-90d7-4c0e-82c1-3acf222e0784)


![image](https://github.com/standards-hub/docs/assets/128386451/db47b7b7-d93b-430d-a6d5-711f7e6d6d56)


![image](https://github.com/standards-hub/docs/assets/128386451/fd78eaaa-36d1-4474-a537-eedeeb4332f8)

It worked for me.

But, what I have noticed is that when navigated back and forward using breadcrumbs, it fails to load files from `affiliates/` and `liaison-agreements/`. So, I have added a full path to those two in `omaspecsworks/collaborate/affiliates/`. 

Here is the [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/40) connected to this issue.
