### ISSUE TITLE
ShButton: Comments

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#115]
These are my findings:
### Properties and Attributes
The following properties/attributes don't seem to work: (see example in `update-shbutton` branch.
- [x] `wrapper`: shadow-2xl
- [x] `rounded`: rounded-full # doesn't work either
- [x] `labelButton`: text #, but in reality, this property is not used to write the label text. Should we hide it from the table?
- [x] `disabled` # what are the possible values? ("on", "off", "true", etc). It stops working with any value.
- [x] `variant`: we are considering calling it `styleButton`, but we should really discuss it before making any changes
- [x] `block` as soon as the property is introduced the width of the button changes independent of the value. We also, discussed to change the name to `widthbutton` but it is not confirmed.
- [x] `type`: (possible values "button, submit or reset") But how does it work, what does it? Should be listed in the properties table?

**Comment by FroudeDescartes** [comment]
@jpradocueva 

- `wrapper: shadow-2xl` works fine in my case
- `rounded: rounded-full` works as well, but it needs to be called through the ui object like you would with `wrapper`
- `labelButton: text` this property is reserved for special use cases like if we want our button to be a part of some larger text, therefore we would use it with inline method (this is explained in guidelines for ShButton starting from line 415) 
- `diasbled: true | false` this prop is boolean type, so it only takes `true` or `false` as values and it disables click on button if set to `true`. Default state is `false`
- `variant` --> discuss in next comment
- `block: true | false` this prop is also boolean type, so it only takes `true` or `false` as values and if set to `true` the button will occupy the whole available width. Default state is `false
- `type` I cannot find what does it do. Maybe @rubystream knows about this one

**Comment by FroudeDescartes** [comment]
**About `variant` prop naming**

When asked ChatGPT to propose a naming for this prop, this is the list that I got (keep in mind that we can add sufix Button to any of propositions):

_**ChatGPT**_
 Here are several potential names for the property, each with a brief rationale for its selection:

- **appearance**: Reflects the overall look and feel of the button.
- **style**: Indicates the styling of the button.
- **theme**: Suggests a cohesive set of visual attributes.
- **variant**: Conveys the idea of different versions or alternatives.
- **type**: General term indicating the kind or category of button.
- **look**: Simple and direct, focusing on the visual aspect.
- **design**: Implies the crafted visual aspect of the button.
- **mode**: Conveys different states or versions.
- **format**: Reflects the arrangement and visual layout.
- **skin**: Refers to the outer appearance, often used in UI contexts.
- **form**: Indicates the shape or structure of the button.
- **presentation**: Focuses on how the button is displayed.
- **display**: Indicates how the button is shown to the user.
- **decoration**: Highlights the aesthetic aspect of the button.
- **visualStyle**: Combines visual and style to clearly indicate the property's purpose.
- **outlineType**: Directly references the outline aspect as one of the options.
- **layout**: Reflects the arrangement and visual presentation.
- **config**: Short for configuration, implying various settings.
- **uiStyle**: Indicates it is a style setting related to the user interface.
- **renderStyle**: Focuses on how the button is rendered visually.

**Comment by FroudeDescartes** [comment]
> `type` I cannot find what does it do. Maybe @rubystream knows about this one

Dejan set the `type` to have a value of `button`, and that is a permanent value. The reason for this is that this constructor is built using **ULink**, which can either be a `button` or a `link`, so we want to force the state of the `button` even if we have it behave like a simple click-to-link.
This is the [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/46)

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/49) related to this issue
