### ISSUE TITLE
Issues with LwM2M index content

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#118]
### Issues when building this [page](https://lwm2m.openmobilealliance.org/):

- [x] If single columns are indented to the right inside of a multicolumn, the rendering of, e.g., background color, doesn't work.
- [x] Update Micro-Card to include icons. See below:
![image](https://github.com/standards-hub/docs/assets/3258579/a2e8cb0b-0b05-4a78-90e4-fa731f8a1c8f)
- [x] How to add padding between micro-cards.See the issue below:
![image](https://github.com/standards-hub/docs/assets/3258579/d120ddd0-a511-4cec-a697-5c456f82e4c4)
- [x] How to reproduce the news/articles section of:
![image](https://github.com/standards-hub/docs/assets/3258579/3d64bd8e-bcec-4463-adfa-6253acd65245)
- [x] In which folder I should add the images?
- [x] ShCard is not working correctly inside a `card` constructor. When deleting some text content from the first `card`, the rest of the cards are updated 
See problems in PR #

**Comment by jpradocueva** [comment]
See content in PR https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/53

**Comment by FroudeDescartes** [comment]
@jpradocueva 
### **1. Issue**
>  If single columns are indented to the right inside of a multicolumn, the rendering of, e.g., background color, doesn't work.

When using `ui` object to insert classes to e.g. `wrapper`, `wrapper` also needs to be indented. 

___

### **2. Issue**

> How to add padding between micro-cards?

We can have two solutions here, one permanent and one that the user needs to input:
1. Permanent - we can add `mt-number` and `mb-number` to the component itself, more specifically add these values to the `wrapper` inside `sh-micro-card.ts` where the number represents the margin value. With these, we need to be careful as every instance of `sh-micro-card` will have those values, and when we want to concatenate more `sh-micro-card` components, these values add up and can produce more spacing than we want
2. User inputted - add` mt-number` and `mb-number` to the` ui.wrapper` object with desired number values (e.g. `mt-3 mb-3`). This needs to be inputted inside of md, as we do it anyway when we need to add additional styles

___

### **3. Issue**

>  How to reproduce the news/articles section

I saw that you have created a request for a new constructor called `ShListCards`. But, I think that we can create that list with `ShMultiColumn` with some minor additions such as adding a `title` and `subtitle` prop. `ShCard` also needs some improvements that you have listed in the new request, and I`ll see to add them. 

___

### **4. Issue**

> In which folder I should add the images?

Images can be added to `public/images` folder. You can just opt out to create additional folders inside, but you'll need to provide a full path to an image as well as the name and extension of the image. 

___

### **5. Issue**

> `ShCard` is not working correctly inside a `ShMultiColumn` constructor. When deleting some text content from the first card, the rest of the cards are updated

To avoid bad rendering, the best practice when using nested components(constructors) is to:
1. indent nested component- if you have one component inside another, you indent once, if you have yet another component nested in an already nested component, then indent it twice, and so on
2. The same level of nested component uses the same number of `:::`, and you can add as much of 
`:::` as you want, but the minimum is **two**

_I have made these changes to the same index file, so for full representation, check my commit._
