### ISSUE TITLE
ShAlert: Issues

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#122]
These are some of the problems identified with the `ShAlert` module:

### About Section of LwM2M
**Example**: See [About OMA SpecWorks](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/53/files) section
**Problem**: The text inside of the About section is not presented correctly; it breaks into two columns after the URL. See image below: 
![image](https://github.com/standards-hub/docs/assets/3258579/7d3d6275-c83d-4c17-96ea-aedaf1eeef24)

**Comment by FroudeDescartes** [comment]
This issue has been resolved within this [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/53/commits)
[Changes](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/53/commits/aad391294007707ac3ed0937f396547284e6bd02)
