### ISSUE TITLE
Move logo and registration to left and right

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#123]
See example. 
We need to move the logo to the left and the login to the right.
<img width="1178" alt="image" src="https://github.com/user-attachments/assets/a77e8dba-fd7a-4a9d-b429-3b38898ddb14">

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/70) related to this issue
