### ISSUE TITLE
[Document-Layout] Identify Issues

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#131]
@rubystream, I have identified the following issues that you may be well aware as the PR is still marked as [WIP]
- [x] Right menus are out of sync when visiting sub-menus
      * See the problem in a short video: https://www.screencast.com/t/D96YJ3TQwKV
This problem has been resolved, but a new problem has appeared.

- [x] In the feature branch `update-add-document-layout', also visible via PR [oma-knowledge-base](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/82). The display of sub-menus inside of sub-folders has stopped working after the latest change.
 * In this branch, `update-add-document-layout` the sub-menu `example1` under folders `8.guidelines` / `2.components` / `1.examples` is not listed after the latest changes.

**Comment by jpradocueva** [comment]
- [x] The website runs okay but provides the following error on the terminal:
```md
[ { title: 'Getting Started',
    _path: '/guidelines/getting-started',
    children: [ [Object] ],
    layout: 'doc' },
  { title: 'Components',
    _path: '/guidelines/components',
    children:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    layout: 'doc' },
  { title: 'Guidelines', _path: '/guidelines', layout: 'doc' } ]
[nuxt] [NuxtLink] You can't nest one <a> inside another <a>. This will cause a hydration error on client-side. You can pass the custom prop to take full control of the markup.
[ { title: 'Getting Started',
    _path: '/guidelines/getting-started',
    children: [ [Object] ],
    layout: 'doc' },
  { title: 'Components',
    _path: '/guidelines/components',
    children:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    layout: 'doc' },
  { title: 'Guidelines', _path: '/guidelines', layout: 'doc' } ]
[nuxt] [NuxtLink] You can't nest one <a> inside another <a>. This will cause a hydration error on client-side. You can pass the custom prop to take full control of the markup.
```

**Comment by FroudeDescartes** [comment]
The object you see in the terminal occurs because a `console.log()` is invoked in line 120. As soon it gets removed, all of this should be gone. Dejan probably used it to check the output, but I will leave it up to him to remove it as I don`t know if he needs it for future reference.
![image](https://github.com/user-attachments/assets/25b04c40-3564-4dcd-84b8-1eaf97a5796c)

**Comment by jpradocueva** [comment]
@rubystream 
We need to reach at least a 4 submenu. See example
![image](https://github.com/user-attachments/assets/b9ce9a79-c511-4b3d-bc29-5c8e8d6b783d)

The fourth submenu is:
![image](https://github.com/user-attachments/assets/4368c408-1a37-4520-a0d8-9c5a8e4392e1)
- [ ] The system cannot render the fourth submenu correctly, as the reference to the parent disappears, creating confusion.
- [ ] The navigation buttons at the end of the page are also out of sync as well.

**Comment by rubystream** [comment]
The first point should be resolved with [PR-91](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/91)

**Comment by jpradocueva** [comment]
Completed.
