### ISSUE TITLE
[DEPLOYMENT] Create GitHub Pages

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#134]
- [ ] Create a `ci/cd` to deploy this content into GitHub Pages

**Comment by FroudeDescartes** [comment]
Google Tag Manager should be installed before deployment

**Comment by jpradocueva** [comment]
Example of deploying from a Private GitHub repository: https://github.com/OpenMobileAlliance/oma_working_groups/blob/master/README.md
