### ISSUE TITLE
[L&F] Tailwind Config OMA Colors

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#135]
- [x] Add OMA colors to `tailwind.config.ts` file with their shades listing from values `50` to `950`

**Comment by FroudeDescartes** [comment]
From official [Nuxt UI documentation](https://ui.nuxt.com/getting-started/theming#css-variables):
"The primary color also has a DEFAULT shade that changes based on the theme. It is `500` in light mode and `400` in dark mode. You can use as a shortcut in your components and pages, e.g. `text-primary`, `bg-primary`, `focus-visible:ring-primary`, etc."

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/90) connected to this issue

**Comment by FroudeDescartes** [comment]
On `development` branch, do a 
```bash 
git pull
```
 and checkout this new feature;

Now, besides the default colors provided by Tailwind, we can use OMA colors and their different shades. 
Classes to use:
- class-**oma-red**-number
- class-**oma-purple**-number
- class-**oma-yellow**-number
- class-**oma-cyan**-number
- class-**oma-blue**-number
where `class` can be `bg`, `text`, `border`, etc., and `number` takes values from 50  to 950 like Tailwinds colors

**Comment by jpradocueva** [comment]
@FroudeDescartes, I work in a new branch,[ lf-1](https://github.com/OpenMobileAlliance/oma-knowledge-base/tree/lf-1), PR, https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/93. I play with the attributes and classes to see the best style. I am starting to use the colors defined above with the icons but I need to extend it to other constructors.

**Comment by jpradocueva** [comment]
Completed.
