### ISSUE TITLE
Aside Menu - Look & Feel

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#136]
### Aside Menu
_Refer to image number:_
1.  - [x] Links: Blue and without underline
2. - [x] Single Menu: Shadow, with a vertical line (primary color)
3. - [ ] Separation line from folder-menu to folder-menu
4. - [ ] Menus with submenus are highlighted by `>`, `V` 
5. - [x] SubMenus: Shadow
6. - [ ] Possibility to add Icons

<img width="416" alt="image" src="https://github.com/user-attachments/assets/a454f4f7-8137-4542-b1ff-eefa159202bb">

**Comment by jpradocueva** [comment]
- [ ] Add the same look & feel on the right menu.
![image](https://github.com/user-attachments/assets/c19a0f4c-5d2a-4b44-9be0-6e774f821848)

- [x] The underline disappear after clicking on the side menu
![image](https://github.com/user-attachments/assets/0fce0479-b9d0-41f3-836a-b5fd2b4b12d3)
- [x] Scrolling the body text should be synced with the menus and submenus

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/137) connected to this issue
