### ISSUE TITLE
[L&F] Light/Dark Mode

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#143]
- [ ]  Each constructor needs be evaluated for dark and light mode.

**Comment by jpradocueva** [comment]
- [x] In dark mode we need to improve hover over links( aside menus)(dark blue is a problem)
![Image](https://github.com/user-attachments/assets/1f24d4e4-7d7a-41c0-b411-4471ef5b29f8)

- [x] Dynamic Tables: In the dark mode, hover over fields in the filter-box is problematic when selecting. 
![Image](https://github.com/user-attachments/assets/e7f42cc7-eacf-4cdf-9ef4-88ded09a14ef)

**Comment by jpradocueva** [comment]
- [x] Light Mode improvements. See related changes in PR https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/210

**Comment by FroudeDescartes** [comment]
Hover bg color in filters in dynamic table resolved in this [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/247)

**Comment by jpradocueva** [comment]
- [x] Web forms from HubSpot don't render correctly in the dark mode. I need to check if it is possible to do something from HubSpot itself to accommodate the website's look and feel.

![image](https://github.com/user-attachments/assets/d015a785-c392-4c55-8093-f10d601e7fdf)

**Comment by jpradocueva** [comment]
- [x]  Contact Us, local link: http://localhost:3000/contact-us
![image](https://github.com/user-attachments/assets/ee2f7447-d5b6-49c5-b085-a5df5c0ad0cd)

**Comment by jpradocueva** [comment]
- [x] The background color of the multitable in the LwM2M menu looks different. It seems the same color as the microcards

![image](https://github.com/user-attachments/assets/1cf17812-3803-4003-9aba-f5551401031a)

Other examples, from Specifications.
![image](https://github.com/user-attachments/assets/61c05a86-f60f-4ff0-91fe-ca289f7dbacf)

**Comment by jpradocueva** [comment]
- [x] Dynamic tables under LwM2M Registries for [Objects](http://localhost:3000/lwm2m/resources/registry/objects#omna-lwm2m-objects) and [Resources](http://localhost:3000/lwm2m/resources/registry/resources#omna-lwm2m-resources)
This is how these dynamic tables look like .... the table is with vertical columns that look old style.

![image](https://github.com/user-attachments/assets/d0797cdf-1a49-4f48-9095-5cc5b7ec04f2)

This look and feel looks better:

We should aim to have the same look and feel on these dynamic tables as in the [Specifications](http://localhost:3000/specifications/search/specifications) _local link_
![image](https://github.com/user-attachments/assets/0900ab6b-05ab-4b86-96a5-dac83003fb65)

**Comment by FroudeDescartes** [comment]
@jpradocueva 
I could not change the style of forms from HubSpot. So those probably need to be changed from HubSpot itself as you said. 
Other changes are done, and can be found under this [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/210)

**Comment by jpradocueva** [comment]
@FroudeDescartes, ok, I will see what can be done from HubSpot.

**Comment by FroudeDescartes** [comment]
Hubspot changes done from Hubspot itself
