### ISSUE TITLE
[Affiliates] Content

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#144]
- [ ]  We need bring the following content https://technical.openmobilealliance.org/Affiliates.html, the repo, https://github.com/OpenMobileAlliance/technical.openmobilealliance.org

**Comment by rubystream** [comment]
@jpradocueva I need a bit of clarification. 
 In the current [Affiliates](https://temp.openmobilealliance.org/omaspecworks/collaborate/affiliates) page the all the child pages are populate except the [WAP Forum](https://temp.openmobilealliance.org/omaspecworks/collaborate/affiliates/wap-forum).
What it the actual task here to populate the WAP Forum page in the same fashion as the other child pages are populated or to bring the Affiliates pages to public folder similar to OMNA ones?

**Comment by jpradocueva** [comment]
@rubystream, Philip was working on that page. This is the latest page left. He did the rest of the pages. Could we apply similar changes you made to the Affiliate's content?
