### ISSUE TITLE
[Miscellaneous] A bit of this a bit of that

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#147]
@FroudeDescartes we need assistance on the following tasks:

- [x]  connect this file [contact us](https://github.com/OpenMobileAlliance/oma-knowledge-base/blob/development/content/contactus.md) with the top right-hand link of the same name `Contact Us'
- [x] I think that we should bring back the old symbol of dark vs light mode. Do you think that this symbol is better than the old one?

![image](https://github.com/user-attachments/assets/22135c34-41ce-4acc-ae12-5fc23dbe9498)

**Comment by FroudeDescartes** [comment]
> @FroudeDescartes we need assistance on the following tasks:
> 
> * [ ]   connect this file [contact us](https://github.com/OpenMobileAlliance/oma-knowledge-base/blob/development/content/contactus.md) with the top right-hand link of the same name `Contact Us'
> * [ ]  I think that we should bring back the old symbol of dark vs light mode. Do you think that this symbol is better than the old one?
> 
> ![image](https://private-user-images.githubusercontent.com/3258579/369688883-22135c34-41ce-4acc-ae12-5fc23dbe9498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMjQ0MTIsIm5iZiI6MTcyNzAyNDExMiwicGF0aCI6Ii8zMjU4NTc5LzM2OTY4ODg4My0yMjEzNWMzNC00MWNlLTRhY2MtYWUxMi01ZmMyM2RiZTk0OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTY1NTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmE1MjU0NmU4ZmM3ZmQ0MGY3YTY2Zjc2YzMxYjJhNTdjMmNjOTliYjFjNzdlNGRlNDcxZDIxZTRiMDljMjczZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.A6POnr0U6LC-a2joEFN7WE-UoXvpaSW7qKI43ifbf5U)

For the dark/Light mode we now have the option to make a theme follow system theme, that is what this icon represents. I like having this option, but if you find it to be too much, or icon not appealing, we can change that any time
