### ISSUE TITLE
[Problem in OMASpecWorks]

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#149]
- [x] For some reason, some of the submenus in the OMASpecWork menu have an error where one part of the page has a different background color than the other half. See below. This problem can be seen when visiting "Contact Us".

![image](https://github.com/user-attachments/assets/3d8c49cf-dc17-4591-9ab9-71efe84e766c)

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/182) resolving this issue
