### ISSUE TITLE
Ability to display multiple documents but under different menus

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#15]

**Comment by jpradocueva** [comment]
Completed in PR #22

**Comment by jpradocueva** [comment]
@FroudeDescartes, I noticed one problem. The right-hand side menu doesn't change after clicking on the top menus, "Markdown" and "GitHub". The body of the content does change, but not the right menu. I am opening the ticket and assign it to you for further evaluation.

**Comment by jpradocueva** [comment]
@FroudeDescartes, I have realized what the problem was, but I don't know how to resolve it. If we want the menus to point to a different document, then we need to create an equivalent `content` folder for each menu. In this way, each top menu will list the content inside of the folder, e.g., `contentx`, and the menus on the left-hand side will be different. I guess that this is one possible solution, but you will need to hack the code to allow multiple `content` folders and link them to each top menu.

**Comment by jpradocueva** [comment]
@FroudeDescartes, maybe the changes need to be applied in the `app.vue` and replicate lines 12 to 22 of that file for each folder containing documents to render independent?

**Comment by FroudeDescartes** [comment]
@jpradocueva I think I might have misunderstood the initial task then. Just so we are on the same page here, what (content) should menus in the Header point to?
At this moment, they are pointing to the `index.md` files for `Markdown` and `GitHub` respectively, and redirecting us to those pages (like a shortcut). 
If I want them to point to a totally different content from the ones that we have for `MD`&`GH`, then yes, new folder in `content` should be created and populated with new and different files.

**Comment by jpradocueva** [comment]
@FroudeDescartes, my requirement is that each time we click on the menu, we see a new refresh of the page content. Meaning:
* A click in the `home` menu takes me to a traditional webpage (no for documentation)
* A click in the `Markdown` menu presents documentation related to Markdown (only). The left-hand side menus provide the titles of the content.
* A click in the `GitHub` menu displays a new page containing only GitHub content. I should not see Markdown content on it.
* We could add further menus, pointing to new and independent content or external resources.

This means that we need to have the ability to relate a `menux` with a folder `contentx`. In this way, we don't need to mix different content, e.g., Markdown and GitHub, on the same page and display it under the same left-hand side menu.

**Comment by FroudeDescartes** [comment]
@jpradocueva 
Ok, now I am in the clear.
I will find an option for the left-hand side menu to be active only on selected content (e.g. If the selected is `Markdown`, the left-hand side menu should only represent `Markdown` content). 
Thx for the fast reply.

**Comment by FroudeDescartes** [comment]
[Documentation](https://content.nuxt.com/get-started/configuration#sources) of the `Content` module targeting this specific issue.

Edit: These issues helped me achieve to resolve this issue, because Nuxt's documentation was not complete and sufficiant

- [Issue 1](https://github.com/nuxt/content/issues/1049)

- [Issue 2](https://github.com/nuxt/content/issues/1788)

**Comment by FroudeDescartes** [comment]
@rubystream
I was able to create separate content folders with local route. Still some more things to change. You can check it out at linked branch.

- [x] Divide content in separate content folders in root

- [ ] Connect external route (some GitHub repo, public or private; See comment above for documentation)

- [ ] UAside component should only show content from active top-level menu (see this [link](https://content.nuxt.com/usage/navigation#self-managed-navigation))

**Comment by jpradocueva** [comment]
This is already possible. We use folder structure, any folder at the root level is equivalent to a new document.
