### ISSUE TITLE
[Fix Aside Menu] 

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#150]
- [x] Check how it looks like to have a fixed aside menu with links to "Newsletter" and "Contact Us"

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/172) connected to this issue

**Comment by jpradocueva** [comment]
@FroudeDescartes there is a display issue with the fixed menu on this page http://localhost:3000/lwm2m/resources#lwm2m-resources
We should keep the "Useful Links" fixed. See the video for details.
https://www.screencast.com/t/aFbwjcdtFEQP

**Comment by FroudeDescartes** [comment]
@jpradocueva 
Ooh yeah, you are right. I will fix that first thing tomorrow
