### ISSUE TITLE
[Dynamic Table] Minor enhancements

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#151]
- [x] Filtered documents should be clickable (add URL type) (check with Dejan)
- [x] Keep the `Quick Filters` deployed by default and compacted by clicking. 
- [x] Add a darker background when selecting elements in the filter

**Comment by rubystream** [comment]
It is addressed in PR https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/170

**Comment by jpradocueva** [comment]
- [x] One less urgent issue is keeping the filter window at the same height, independent of the number of elements selected. At the moment, the window's height adjusts to the number of objects selected. In the Technical pages, this height is fixed, and I believe that it improves the user experience.
