### ISSUE TITLE
[Landing Page] Update

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#154]
- [ ] ~Carousel at the top (smaller)~
- [ ] ~Table (microcards) (smaller)~
- [ ] ~Other text~

**Comment by FroudeDescartes** [comment]
pages/index.vue needs to be altered

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/209) connected to this issue

**Comment by jpradocueva** [comment]
- [ ] Add search function

**Comment by jpradocueva** [comment]
It was added floating microcards.
