### ISSUE TITLE
[Buttons in Dark Mode] Missing Shadow Effect

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#166]
- [ ] In Dark Mode the shadow effect of a button is not visible. See below
* Light Mode
![image](https://github.com/user-attachments/assets/d5fc549f-d1b1-42a3-ad0b-34aba09632ca)

* Dark Mode
![image](https://github.com/user-attachments/assets/7298afbc-bf4d-4fb1-b20e-0d8483373684)

**Comment by FroudeDescartes** [comment]
Shadow is always of dark tonality. It represents the presence of light. In the dark mode, you have abscenes of light so we don\`t have shadows. Even if we could introduce it, it cannot be with `shadow-[intensity]` class, so we must create a workaround.

**Comment by jpradocueva** [comment]
Ok, I see. Thanks!. Let's keep it as P2 as this is not a big issue at this time.

**Comment by FroudeDescartes** [comment]
I have just remembered that we can change the color of the shadow by using one additional class to to shadow invoke class. I will do a few examples just so we can check it out
https://tailwindcss.com/docs/box-shadow-color
