### ISSUE TITLE
[TABLES] Harmonization

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#167]
@FroudeDescartes:
- [x] For some reason, many tables were incorporated with a script. We should try to harmonize all these tables and have as little as possible inline-style in the tables.

See the example in Events/Member Meetings.

<img width="1475" alt="image" src="https://github.com/user-attachments/assets/fa8e8a91-9c7f-4d2b-8c4f-0bc24afd5d87">

**Comment by FroudeDescartes** [comment]
I have tried to avoid this in md files, as you might see in `app.vue` file under `<style>` section where I have inserted a global style for tables. This is one that missed my eye. I hope it is the only one :D 
Will see to remove any unnecessary styles in md files.

![image](https://github.com/user-attachments/assets/940ae094-4d38-4f72-aeba-9d9adefbb529)
_Global style for tables_

**Comment by jpradocueva** [comment]
@FroudeDescartes, oh, ok, that's great that you have already done that. I missed it.
