### ISSUE TITLE
[Unable to render _8.guidelines]

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#174]
How to display hidden content.

**Comment by FroudeDescartes** [comment]
Resolved in [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/421)

**Comment by FroudeDescartes** [comment]
Testing with this [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/428)

**Comment by FroudeDescartes** [comment]
Issue resolved with this [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/435)
