### ISSUE TITLE
[Proxy] not providing right content

### ISSUE THREAD

**Issue by rubystream** [standards-hub/docs#189]
When page is rendered from https://openmobilealliance.org/oma-events/test-events the the content is not provided:

![openmobilealliance org_oma-events_test-events](https://github.com/user-attachments/assets/2f950bf7-e4c5-4948-8052-ef17aeb71c6d)

While when taken directly from https://oma-knowledge-base.openmobilealliance.org/oma-events/test-events

![oma-knowledge-base openmobilealliance org_oma-events_test-events](https://github.com/user-attachments/assets/7f6b7616-6de6-400a-a61c-f7da6b79d38b)

It seams like the issue is with **reverse-proxy** as that in console the error provided is:
```
/specifications/:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by jpradocueva** [comment]
This is the list of pages that render correctly for a few milliseconds, and then the content disappears:
- [x] https://openmobilealliance.org/contact-us
- [x] https://openmobilealliance.org/lwm2m/resources
- [x] https://openmobilealliance.org/oma-events/members-meetings
- [x] https://openmobilealliance.org/oma-events/test-events
- [x] https://openmobilealliance.org/oma-events/webinar-workshops
- [x] https://openmobilealliance.org/tools/lwm2m-api-registry/
- [x] https://openmobilealliance.org/tools/validation-errors
- [x] https://openmobilealliance.org/lwm2m/community/product-listing
- [x] https://openmobilealliance.org/lwm2m/resources/lwm2m-enablers
- [x] https://openmobilealliance.org/lwm2m/resources/tutorials-guidelines
- [x] https://openmobilealliance.org/omaspecworks/membership/benefits
- [x] https://openmobilealliance.org/specifications/api/abstract
- [x] https://openmobilealliance.org/specifications/api/http
- [x] https://openmobilealliance.org/specifications/api/soap
- [x] https://openmobilealliance.org/specifications/api/webidl
- [x] https://openmobilealliance.org/specifications/registries/enablers
- [x] https://openmobilealliance.org/specifications/registries/supporting-data
- [x] https://openmobilealliance.org/specifications/search/public-docs
- [x] https://openmobilealliance.org/utilities/market-potential/whitepaper-lwm2m-metering-use-case
- [x] https://openmobilealliance.org/lwm2m/resources/registry/objects
- [x] https://openmobilealliance.org/lwm2m/resources/registry/resources
- [x] https://openmobilealliance.org/omaspecworks/collaborate/affiliates/in-location-alliance
- [x] https://openmobilealliance.org/omaspecworks/collaborate/affiliates/location-interoperability
- [x] https://openmobilealliance.org/omaspecworks/collaborate/affiliates/mobile-games-interoperability
- [x] https://openmobilealliance.org/omaspecworks/collaborate/affiliates/mobile-wireless-internet-forum
- [x] https://openmobilealliance.org/omaspecworks/collaborate/affiliates/wireless-village


These pages have a display problem in light mode. The font is mixed with the white background.
- [x] https://openmobilealliance.org/announcement 
- [x] https://openmobilealliance.org/landing-page-floaters

These pages cannot be found:
- [x] https://openmobilealliance.org/contact_us 
- [x] https://openmobilealliance.org/lwm2m/contact-us
- [x] https://openmobilealliance.org/news/articles/2020-01-23-Lw2M2M-5G
- [x] https://openmobilealliance.org/lwm2m/community/www.ioterop.com/iowa
- [x] https://openmobilealliance.org/utilities/market-potentialwhitepaper-lwm2m-metering-use-case

What are these pages?
- [x] https://openmobilealliance.org/news/articles/

**Comment by Evadon-Nathan** [comment]
- I have fixed the redirect issue.

- The light mode text issue is not a server issue and needs to be fixed in the code.

- Those pages can't be found because they don't exist. Do you need extra redirects adding for them?

- I don't know what this page is:  https://openmobilealliance.org/news/articles/

**Comment by FroudeDescartes** [comment]
1. Pages that have a display problem in light mode:
     - This should not be considered as a concern since these files are not available as links anywhere on site. They are used for landing page content.
2.  Pages that cannot be found:
     - https://openmobilealliance.org/contact_us this page really does not exist, we only have it in this form [https://openmobilealliance.org/contact-us](https://openmobilealliance.org/contact-us)
     - https://openmobilealliance.org/lwm2m/contact-us as I recall, this was removed and relocated under https://openmobilealliance.org/lwm2m/contact-us
     - https://openmobilealliance.org/news/articles/2020-01-23-Lw2M2M-5G for links Nuxt creates everything in kebab lower case, so `LwM2M-5G` makes it invalid as URL adress
     - https://openmobilealliance.org/lwm2m/community/www.ioterop.com/iowa I don\`t know what is this link-we don\`t have any folder/file named like this; my best guess is that somewhere in `../community` folder there is this  www.ioterop.com/iowa link but for some reason it gets interpreted as a `content` item
     - https://openmobilealliance.org/utilities/market-potentialwhitepaper-lwm2m-metering-use-case this is incorrect as it need forward slash between `../market-potential` and `whitepaper-lwm2m-metering-use-case`; https://openmobilealliance.org/utilities/market-potential/whitepaper-lwm2m-metering-use-case - this is correct link and it works from website
3. What are these pages:
     - https://openmobilealliance.org/news/articles/ we used this to show article and navigate to it before aside navigation; this is to be DELETED
     
Conclusion:
There will only be one action required, and that is deleting `https://openmobilealliance.org/news/articles/` file ([PR for this](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/349)). Everything else is lapsus calami or invalid paths.
