### ISSUE TITLE
Icons not rendering in production

### ISSUE THREAD

**Issue by FroudeDescartes** [standards-hub/docs#197]
This could be due to a new update to v1. Checkout:
- https://nuxt.com/modules/icon
- https://github.com/nuxt/icon/pull/154

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/422) connected to this issue.

**Comment by FroudeDescartes** [comment]
- [ ] @jpradocueva 

- [ ] @gocadimic 

Can you check if the icons render correctly on our live version?

**Comment by jpradocueva** [comment]
@FroudeDescartes  Something needs to be fixed for me. When I click on any of the main menus, the icons don't download. I need to refresh the page to see the icons.

**Comment by jpradocueva** [comment]
@FroudeDescartes was the patch applied to production? My test was in production.

**Comment by FroudeDescartes** [comment]
@jpradocueva  
I have applied the patch to production, but it seems that it is not working. In `dev` everything appears correctly.
I will keep searching for a solution, and until I fix it in production, I am leaving this issue open.

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/434) resolving this issue
