### ISSUE TITLE
[Dynamic Table] Missing  "hide" property from Guidelines

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#203]
Please cross-check the `hide` property. It seems missing from the description of the guidelines.
See example where it appears: line 98 of https://github.com/OpenMobileAlliance/oma-knowledge-base/edit/dev/content/3.lwm2m/30.resources/05.registry/10.objects.md

**Comment by FroudeDescartes** [comment]
Looks like I have missed it. I will make sure to add it in following PR

**Comment by FroudeDescartes** [comment]
Resolved in [PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/459)
