### ISSUE TITLE
Creation of breadcrumbs 

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#35]
To be added to each page.

**Comment by rubystream** [comment]
Here is the document about [breadcrumbs](https://ui.nuxt.com/navigation/breadcrumb) usage.

**Comment by jpradocueva** [comment]
Thanks Dejan!

**Comment by rubystream** [comment]
Works as expected. Need some more styling that can be done in some latter phase.

**Comment by FroudeDescartes** [comment]
@FroudeDescartes 
Make the active page highlighted (like a link).

**Comment by FroudeDescartes** [comment]
@jpradocueva 
Highlighted an active crumb and inserted a `&nbsp` in front and after a divider
