### ISSUE TITLE
Ability to input a primary color with hexadecimal or RGB

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#36]
Update `app.config.ts` primary value.
Same for `gray` value

**Comment by FroudeDescartes** [comment]
https://ui.nuxt.com/getting-started/theming
https://tailwindcss.com/docs/customizing-colors#using-custom-colors
https://tailwindcss.com/docs/customizing-colors#adding-additional-colors
https://uicolors.app/create

**Comment by jpradocueva** [comment]
This is resolved.
