### ISSUE TITLE
Find out how to add by default PR and Issues to the Project "Docs"

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#4]

**Comment by FroudeDescartes** [comment]
Update:
Solution for connecting `PR`s to `Docs`

![Image](https://github.com/standards-hub/docs/assets/128386451/9933c058-12a8-4b1a-bb99-7632b99c7bbf)

It should be manually connected as shown in the red box in the picture.

**Comment by jpradocueva** [comment]
@FroudeDescartes, thanks. You uncovered the problem.

The problem was that by setting the filter that a label has to be added it forces that even the PR needs to have a label.
I removed the filter of `Priority`, and I tested by creating Issue #29 and PR #30, and both appear automatically in the Backlog column.

**Comment by jpradocueva** [comment]
Now, we can close this Issue.
