### ISSUE TITLE
Check it out - New Markdown Editor integrated into Nuxt!

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#46]
Check out our [release video!](http://url8360.nuxt.studio/ls/click?upn=tkaxc-2BU54zxteBMuNfryFCUvxa7I3vXr7NUz-2Fzx-2FqvWLhmKtjzVRsW32OkfkAHMC1ksnxns-2Fu7DKRBImf34ExbjCXw6hosbb4RZI2b18Ljc-3DmaGu_-2BhUgu6Uz7rKZq9IIFt546bVsbatuT5id94-2F-2FE11pxS5LtPxO73cxLsX9pc5dSbx8nhuS5-2FhaJvCLglr-2B14wzRn7fvwWObFSPCgHkiaiXLidmigEYqLt-2BpneL8DwyV-2BDhLLckmpji7mOSnIthEfQrQ9RHr6KKMHn7c2J4gSK7dzKeIHPokY-2F6fRl5-2BGe-2F8xX-2FM-2BaX2z1zCYDqCUk5lFPeMQv7sVKeHE1g9B1FaV4PEDp7QSKZKiSqOW9chFxMOS2-2BYPoHMXWOwJZriPOilegY3ki7tb3NMyd0yfXUna3AtxDluc4XOApup1hzADTbeMU1cOzYmUVcSv4YAFRKmR3ik-2FWBhQOlEkRJSBJ5EV5nHixC3Gg5nxY-2BNiBsP3FM55Y4MVyRH0xmoRpFwHCy-2BmmVy5AL00L3-2BceaBzY-2FtETAdGyt2UJzYrVbMKLIYNBmWz-2BnKAw8ZIn5izZrDrAmZLtj6ua-2FaoHx1yGngluTJ3iWZaR17L-2BP9mcdgM6mWRe7pGqc5nJVoLaIFbx0H37-2F086EEnItNllIM5IG43mhDj38G-2B0h4ptyiWNnJspsdxhXNgls-2F8Rl7w2OmgzgDnt5egjZS7f3EvYKpWgZJBvAM2upP-2FcQ-2B-2FapNLSdm-2BDHJz4bm-2Bw0WZfBJ026Hb9ilCtb2QhXoRSilksEFsUzDAJobSNKxmajvMVbw2j7CaGQMKkelYVTpPVIT80nJeTWfymRh7pBd7FnnYR7VjKBHQM-2FYKZKk6r-2FTCW01pNKglKeV3evxZSvGVdfe6i2zKvLHCdAI7Lk6BH4Z8tUq37UH9lWcvigNr7NixVMFCUL9ahRcir6hssN8HmFaGoq0eqOJTc8iarXorUFBmhWQtnz8bqw1cw7Dwi-2FsIMbYvDLBHqvATHLQQGApGuWmi5B-2F-2BMMUwQJH3VKIrdWHnUY5mItBW4kzjyjDuO1YCezUqDWTdtUMWsaziXS-2F89JpggMzI7L8JIMO6fIQ2rDvtSkQ4rYuMzk-2B9L0PlRAx1Upfm1sqAd2UYNS-2BBa-2BgAfI-2F-2B6Yx67H0HmRCKP1W5ECK80QYhGXbu7CzROdjB0-3D)

It is in Beta, but it promises to be a great tool to improve markdown editing, and we should check if we can use it as our Markdown Editor.
I will forward the email that I got from Nuxt. You may have also received it.

**Comment by FroudeDescartes** [comment]
@jpradocueva 
I can not remember if I have read it somewhere already in some of our conversations, nevertheless, this resembles Notion workflow so much. So this is something that is definitely worth of our attention since it is already familiar to all that have used Notion, which is probably not a small number. 
Will take a closer look for our next meeting.

**Comment by jpradocueva** [comment]
From Dejan:
<blockquote >
Hi guys,

This tool is interesting as it uses the git to store the content of the nuxt site, but also a separate service, most probably AWS S3, to show preview deployments.
In general each user gets a branch for their working session. Each branch gets assigned an AWS S3 bucket where they build site content and enable its preview.

Interesting for sure.

Still have not seen if they are supporting the collaborative work of multiple users on the same doc at the same time.

We should monitor their progress for sure.

Dejan
</blockquote>

**Comment by FroudeDescartes** [comment]
https://nuxt.studio/changelog/v1.6.0

**Comment by jpradocueva** [comment]
This requires payment.
