### ISSUE TITLE
Pluralize and Singularize any Word using the ‘pluralize’ NPM Module

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#68]
Please check this module that already provides plurals for any keyword.

https://www.geeksforgeeks.org/pluralize-and-singularize-any-word-using-the-pluralize-npm-module/

**Comment by FroudeDescartes** [comment]
Todays tasks:

- [x] create a repo called MD2HTML_RegEx_Tools _(create it in [S-H](https://github.com/standards-hub) )_
- [x] install pluralize module
- [x] create a `.js` file that will run and create a plural out of an array of words
- [x] create a `.js` file that will run and create a singular out of an array of words

- [x] check how library behaves if we want to pluralize a plural (and vice versa)
