### ISSUE TITLE
Unable to change font size

### ISSUE THREAD

**Issue by FroudeDescartes** [standards-hub/docs#71]
I am trying to change a font size, but whatever I try, font size stays the same.
For changing the font family in codeblocks, I had to create a `assets/css` folder with `main.css` component inside that will regulate font family, but even there, inside of those properties I was unable to change the font size and font weight.

Currently, this issue is resolving on a branch issue-63-elastic-hub.
This ticket is related to #63

**Comment by rubystream** [comment]
![Screenshot from 2024-03-16 20-14-15](https://github.com/standards-hub/docs/assets/3200/2157df27-8a61-471c-8681-9f911a53679f)

When I try a version from the mentioned branch I see that the required font is loaded. 

It is not clear to me where the size and height needs to be observed. @FroudeDescartes can you point me in the right direction?

**Comment by FroudeDescartes** [comment]
@rubystream 
Nuxt documentation is not very clear on to how the font size should be changed.
This is all the Nuxt provides for this topic -> [Styling](https://nuxt.com/docs/getting-started/styling#working-with-fonts)
I tried adding Tailwind classes to `[...slug].vue` file for sections that are of interest, as well in `layouts/docs.vue` without the result. 
[This is one file](artiglom.com/en/custom-font-size-classes-in-vuetify-js-and-nuxt-js) that may help us, but it looks way to complicated for just changing the size of fonts. 
However, I will try it in Monday

**Comment by FroudeDescartes** [comment]
[PR](https://github.com/OpenMobileAlliance/oma-knowledge-base/pull/56) resolving this issue
