### ISSUE TITLE
GitHub announcement - how is this affecting us

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#77]
https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/

See the announcement that we received today from GitHub regarding GitHub Pages. How is this affecting what we have?
GitHub
Hello,

We are writing to inform you about an important update regarding GitHub Pages.

What is happening?

Delivering on our continued commitment to enhance security, protect your data, and deliver an overall improved experience, we will be phasing out our legacy pagesworker architecture by the end of June 2024.

What is replacing legacy pagesworker?

Since [August 2022](https://app.github.media/e/er?s=88570519&lid=6003&elqTrackId=34039ed1b1d24317a13d9bdd6bd0d4fd&elq=1f9d3599cd0e4c7c950b9474bce4a8e5&elqaid=4052&elqat=1), GitHub Pages sites have been built and deployed with GitHub Actions. However for repositories where Actions is unavailable, we used the legacy pagesworkers for Pages builds and deployments.

Going forward, GitHub Actions will become a requirement for deploying Pages sites that require a build step, such as those utilizing Jekyll. We chose to implement this change because Actions provides developers a modern, secure sandbox that surpasses the capabilities of pagesworker. With Actions you get your choice of operating system, log streaming, dependency caching, custom gates, and modern CI/CD features. Additionally, we are pleased to announce the general availability of the [feature](https://app.github.media/e/er?s=88570519&lid=6002&elqTrackId=4dd48b6709014265b0d5f81738064979&elq=1f9d3599cd0e4c7c950b9474bce4a8e5&elqaid=4052&elqat=1) allowing you to delegate Pages deployments to Actions alongside a source branch.

How can I tell if my Pages site will be impacted?

If your Pages site is being built by the legacy infrastructure, a warning message will be displayed in your Pages settings starting today. Note that the vast majority of pages sites have already been leveraging Actions. We only fall back to the legacy build infrastructure if Actions is unavailable in your repository.

We understand that change can be challenging, and we apologize for any inconvenience this may cause. Our priority is to continue delivering a more secure platform for all of our users, and we appreciate your understanding as we make these necessary adjustments.

If you have any questions or concerns about this announcement, please don't hesitate to [reach out to our support team for assistance](https://app.github.media/e/er?s=88570519&lid=6001&elqTrackId=c498aee2bf1c4b21af488eeb40500a7e&elq=1f9d3599cd0e4c7c950b9474bce4a8e5&elqaid=4052&elqat=1). We are here to help and ensure a smooth transition for all our users.

Thank you for being a valued member of the GitHub community.

GitHub

**Comment by FroudeDescartes** [comment]
@jpradocueva 
I have a rough idea about the topic that they are discussing, but since I haven't had any experience with site deployment using GitHub, I will need to take a closer look and probably consult [Dejan](@rubystream ) about it as well. At our meeting on Friday I will have definite answer.

**Comment by jpradocueva** [comment]
@FroudeDescartes Thanks, Filip; we will discuss it on Friday.
