### ISSUE TITLE
Improve textImg component

### ISSUE THREAD

**Issue by FroudeDescartes** [standards-hub/docs#80]
**This is connected to issue #76** 
Add options for this component to:

- [x] add title prop
- [x] present only the text (text is still able to span multirows)
- [x] change the bg color (have it like a status: on, off, pending, higlight)
- [x] ~~overview- this is only for developers, so they will know what does this component do~~ description (default value explains how to use component if no description is inserted)
- [ ] layout (idea is to ~~maybe create a single .js file that will contain Class, which can be later down the road inherited to the desired component an reused the prop~~ create a single component, instead of couple of them, that can have all the necessary logic integrated and used depending on layout selection)

@jpradocueva can you attach here, or send me on Slack a spreadsheet file that represents usecases for different properties  in different components?

**Comment by FroudeDescartes** [comment]
Fix:

- [ ] bg img

**Comment by jpradocueva** [comment]
@FroudeDescartes I am closing this issue. `Layout` property is not a priority in this development. The rest of items have been completed.
