### ISSUE TITLE
[FEATURE] MENU BUTTON 

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#88]
### Example
<img width="1455" alt="2024-04-16_17-18-17" src="https://github.com/standards-hub/docs/assets/3258579/f8b0b71f-cddc-41c8-abb2-aa9a43c6befa">

### Properties
- [ ] Button Title
- [ ] URL
- [ ] Background Color

### Constraints
We need to figure out how we can use classes to manipulate attributes like background color, font size, font text, border, padding, etc

**Comment by FroudeDescartes** [comment]
@jpradocueva 
We already have a search functionality in _docs_ repo, but that is a UI Pro feature. Should I aim to create a new independent search?

Additionally, [`button`](https://ui.nuxt.com/components/button) component is a Nuxt UI feature, so it is free to use, and it has available all of the listed props right out of the box.

**Comment by jpradocueva** [comment]
This is completed.
