### ISSUE TITLE
Ability to present commands or code under different languages

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#9]

**Comment by FroudeDescartes** [comment]
@jpradocueva 
After starting the website locally, visit [this](http://localhost:3000/getting-started) link to see implementation.

Project [`Docs`](https://github.com/orgs/standards-hub/projects/5/views/1) links to tickets:
#9

**Comment by jpradocueva** [comment]
@FroudeDescartes, thanks. It looks good.  To run this functionality, do we need to add any dependencies to the `package.json` file? I would like to know if we need to install or active anything or if this feature is provided by default.

**Comment by jpradocueva** [comment]
Markdown content: PR #23 
@FroudeDescartes, are the images/icons uploaded automatically? I don't see any reference to icons in the PR.

**Comment by FroudeDescartes** [comment]
@jpradocueva 
In short, if we want to use default icons **nothing** needs to be added to `package.json`. Icons that are more specific and aren`t available by default we need to configure (later in a comment about this).

### **Default icons**
When specifying the name of a cards in a `CodeGroup` or `CodeBlock`, an icon will be automatically displayed based on the extension or the name of the file. Important is to envelop the extension or name in angle brackets [ ]. e.g.:


**CodeGroup**
>::code-group
>
>\```bash [**npm**]
>npm install @nuxt/ui-pro
>\```
>
>\```bash [**app.vue**]
>_some code here_
>\```
>
>\```bash [**md**]
>_and some more text in md here_
>\```
>\::

<br>

**CodeBlock**
>\```ts [**nuxt.config.ts**]
>_more code_
>\```

Here is the list of default mapping of icons that are ready to use (in angle brackets just type in the desired extension or name found on the left side of the colon)
```bash
{
  'package.json': 'vscode-icons:file-type-node',
  'tsconfig.json': 'vscode-icons:file-type-tsconfig',
  '.npmrc': 'vscode-icons:file-type-npm',
  '.editorconfig': 'vscode-icons:file-type-editorconfig',
  '.eslintrc': 'vscode-icons:file-type-eslint',
  '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
  '.eslintignore': 'vscode-icons:file-type-eslint',
  '.gitignore': 'vscode-icons:file-type-git',
  'yarn.lock': 'vscode-icons:file-type-yarn',
  '.env': 'vscode-icons:file-type-dotenv',
  '.env.example': 'vscode-icons:file-type-dotenv',
  '.vscode/settings.json': 'vscode-icons:file-type-vscode',
  '.nuxtrc': 'vscode-icons:file-type-nuxt',
  '.nuxtignore': 'vscode-icons:file-type-nuxt',
  'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
  'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
  ts: 'vscode-icons:file-type-typescript',
  tsx: 'vscode-icons:file-type-typescript',
  mjs: 'vscode-icons:file-type-js',
  cjs: 'vscode-icons:file-type-js',
  js: 'vscode-icons:file-type-js',
  jsx: 'vscode-icons:file-type-js',
  md: 'vscode-icons:file-type-markdown',
  ico: 'vscode-icons:file-type-favicon',
  npm: 'vscode-icons:file-type-npm',
  pnpm: 'vscode-icons:file-type-pnpm',
  npx: 'vscode-icons:file-type-npm',
  yarn: 'vscode-icons:file-type-yarn',
  bun: 'vscode-icons:file-type-bun',
  yml: 'vscode-icons:file-type-yaml',
  terminal: 'i-heroicons-command-line'
}

```
<hr/>

### **Special icons**
For icons that are not here by default, we have to add them to `app.config.ts`  through the` ui.content.prose.code.icon key`:

```bash
export default defineAppConfig({
  ui: {
    content: {
      prose: {
        code: {
          icon: {
            facebook: 'i-simple-icons-facebook'
          }
        }
      }
    }
  }
})

```


This is an extensive answer but this will be provided as well in `setup.md` file. 
Documentation about this can be found on [THIS](https://ui.nuxt.com/pro/components/prose/code-block#icon) link.

**Comment by jpradocueva** [comment]
Applied PR #32 adding new codeblock, special icons, and index file.
